name: Python Script Execution

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '55 */5 * * *' # Every 5 hours 55 mins

env:
  CHATBOT_START_PROMPT: ${{ secrets.CHATBOT_START_PROMPT }}
  HUGGINGFACEEMAIL: ${{ secrets.HUGGINGFACEEMAIL }}
  HUGGINGFACEPASSWORD: ${{ secrets.HUGGINGFACEPASSWORD }}
  SCRATCH_PASSWORD: ${{ secrets.SCRATCH_PASSWORD }}
  SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Execute Python script
      run: python main.py
